package ba.unsa.etf.rpr.business;
import ba.unsa.etf.rpr.dao.DaoFactory;
import ba.unsa.etf.rpr.domain.User;
import ba.unsa.etf.rpr.exceptions.HotelException;

import java.time.LocalDate;
import java.time.Period;

public class UserManager {



    public User add(User user) throws HotelException {
        if (user.getId() != 0){
            throw new HotelException("ID is autogenerated");
        }

        Period intervalPeriod = Period.between(user.getBirth_date(), LocalDate.now());
        if (intervalPeriod.getYears() < 18){
            throw new HotelException("User has to be adult");
        }

        try{
            return DaoFactory.usersDao().add(user);
        }catch (HotelException e){
            if (e.getMessage().contains("UQ_NAME")){
                throw new HotelException("Category with same name exists");
            }
            throw e;
        }
    }

}
